name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    services:
      keycloak:
        image: quay.io/keycloak/keycloak:22.0.3
        ports:
          - 8180:8080
        env:
          KEYCLOAK_USER: admin
          KEYCLOAK_PASSWORD: admin
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          url: http://localhost:8080/realms/master/protocol/openid-connect/token
          client_id: admin-cli
          username: admin
          password: admin
      - name: Access output values
        run: |
          echo "Access Token: ${{ steps.oidc.outputs.access_token }}"
          echo "Refresh Token: ${{ steps.oidc.outputs.refresh_token }}"
          echo "Expires In: ${{ steps.oidc.outputs.expires_in }}"
          echo "Refresh Expires In: ${{ steps.oidc.outputs.refresh_expires_in }}"
